name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:

jobs:

  get-runner-for-tests:
    runs-on: ubuntu-latest
    outputs:
      matrix: "${{steps.matrix.outputs.matrix}}"
    steps:
      - id: matrix
        name: matrix
        run: |
          echo '::set-output name=matrix::{"include": [{"name": "cypress-main", "runner": "self-hosted"}, {"name": "cypress-amm", "runner": "self-hosted"}, {"name": "cypress-polygon", "runner": "self-hosted"}]}'
  
  check_matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.get-runner-for-tests.outputs.matrix)}}
    needs:
      - get-runner-for-tests
    steps:
      - name: print
        run: |
          echo ${{needs.get-runner-for-tests.outputs.matrix}}
          echo "${{matrix.name}}:${{matrix.runner}}"
