# example from https://stackoverflow.com/questions/59977364/github-actions-how-use-strategy-matrix-with-script

name: build
on: pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: {"include": [{"name": "cypress-main", "runner": "ubuntu-latest"}, {"name": "cypress-amm", "runner": "ubuntu-latest"}, {"name": "cypress-polygon", "runner": "ubuntu-latest"}]}
    steps:
    - run: echo ${{ matrix.project }}
    - run: echo ${{ matrix.config }}
